### ISSUE TITLE
Theoretical questions about your approach

### ISSUE THREAD

**Issue by meier-johannes94** [chuangg/tdw-transport-challenge-starter-code#7]
@abhi1092 

I have a few questions about the challenge, the code here and also wrt. to the paper "The ThreeDWorld Transport Challenge". If you are the wrong person for this, then maybe somebody else can help me: 

- I do not fully understand yet how `h_agent` works even after looking for a longer time at the code. Especially it seems to me as if he only creates a local occupancy map of his current view and not of the whole scene. If so, I wonder why you created an additional agent instead of publishing the code from the paper. Am I correct with this? If not, how did you implement this? 
- To me it is not clear how you get the occupancy map for Pure RL, RL Exploration and Frontier Exploration? Of course if you are only speaking about the local occupancy map, then you can use the code from h_agent. But the wording in the paper sound to me like you are using the global occupancy map for them. Also for Action Exploration and Semantic exploration you are using their inbuilt functionality to create the occupancy maps, correct? And also how do you create the semantic maps? 
- Is it possible that you also publish the code of the paper? 

Thanks a lot!

**Comment by abhi1092** [comment]
The `h_agent` code estimates a local occupancy map from the depth images and then uses that to update the global occupancy map (I believe that is line `233`). The occupancy map creation remains the same in all the cases. The different exploration techniques (Pure RL, RL Exploration, and Frontier Exploration) simply use this as input. The semantic map uses the segmentation map as an additional input along with depth images. The segmentation mask tells you the exact category of the object occupying a certain set of pixels.
